[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: set the Node.js version used by Netlify build image
[build.environment]
  NODE_VERSION = "20"


